name: tests
on:
  push:
  pull_request:

jobs:
  test:
    name: run tests with code coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.17"
          - "1.16"
          - "1.15"
          - "1.14"
          - "1.13"

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - run: go version

      - name: install lambda runtime interface emulator
        run: curl -L -o /usr/local/bin/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie-x86_64
      - run: chmod +x /usr/local/bin/aws-lambda-rie 

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: go test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
          env_vars: GO
        env:
          GO: ${{ matrix.go }}

